### PR TITLE
contumaliae -> contumeliae

### PR DESCRIPTION
**Pull request by tjmills-dev**

### CODE REVIEW

**Review by Aurorum — APPROVED** [review]

**Comment by Aurorum** [comment]
Thank you, and good luck for the exam!!

**Comment by Aurorum** [comment]
@GeekPro101 How did you find the Language papers?!

**Comment by tjmills-dev** [comment]
@Aurorum difficult to know really, I don't think I did that badly on the translation but who knows for composition. Wbu?

**Comment by Aurorum** [comment]
@GeekPro101 Glad to find somebody else who did the Composition - quite literally the hardest passage which I've ever seen OCR use, so really struggled with it. I think Paper 1 was comparatively better, but still had a lot of odd bits...which set texts do you do?

**Comment by tjmills-dev** [comment]
I do Cicero for prose then Virgil + Ovid for my lit, what do you do

**Comment by tjmills-dev** [comment]
I'm going to add an @Aurorum not sure if GH notifies otherwise

**Comment by Aurorum** [comment]
@GeekPro101 Ah, Cicero + Apueleius for prose and then Virgil all the way through for Verse. Sort of feeling nervous about tomorrow due to the need to make up for Paper 2 being a flop...how are you approaching it? Have you just memorised the translation?

**Comment by tjmills-dev** [comment]
> @GeekPro101 Ah, Cicero + Apueleius for prose and then Virgil all the way through for Verse. Sort of feeling nervous about tomorrow due to the need to make up for Paper 2 being a flop...how are you approaching it? Have you just memorised the translation? 

@Aurorum I've 'memorised' it, but I've got law in the morning and tbh I'm a bit fucked

**Pull request merged**
